import type { RagnarokMvp } from '@/containers/TrackingContainer/types.ts'

export default [
    {
        id: 1,
        name: 'Amon Ra',
        map: 'moc_pryd06',
        spawnTime: { minMinutes: 60, maxMinutes: 70 },
        sprite: '1511.png',
        timeOfDeath: null,
    },
    {
        id: 2,
        name: 'Angeling',
        map: 'pay_fild04',
        spawnTime: { minMinutes: 60, maxMinutes: 90 },
        sprite: '1096.png',
        timeOfDeath: null,
    },
    {
        id: 3,
        name: 'Angeling',
        map: 'xmas_dun01',
        spawnTime: { minMinutes: 60, maxMinutes: 90 },
        sprite: '1096.png',
        timeOfDeath: null,
    },
    {
        id: 4,
        name: 'Angeling',
        map: 'yuno_fild03',
        spawnTime: { minMinutes: 60, maxMinutes: 90 },
        sprite: '1096.png',
        timeOfDeath: null,
    },
    {
        id: 69,
        name: 'Angeling',
        map: 'mjolnir_04',
        spawnTime: { minMinutes: 30, maxMinutes: 40 },
        sprite: '1096.png',
        timeOfDeath: null,
    },
    {
        id: 5,
        name: 'Archangeling',
        map: 'yuno_fild05',
        spawnTime: { minMinutes: 60, maxMinutes: 63 },
        sprite: '1388.png',
        timeOfDeath: null,
    },
    {
        id: 102,
        name: 'Assassin Cross Solo',
        map: 'lhz_dun03',
        spawnTime: { minMinutes: 45, maxMinutes: 82 },
        sprite: '5481.gif',
        timeOfDeath: null,
    },
    {
        id: 103,
        name: 'Assassin Cross Summon',
        map: 'lhz_dun03',
        spawnTime: { minMinutes: 100, maxMinutes: 130 },
        sprite: '5481.gif',
        timeOfDeath: null,
    },
    {
        id: 8,
        name: 'Atroce',
        map: 'ra_fild04',
        spawnTime: { minMinutes: 300, maxMinutes: 310 },
        sprite: '1785.png',
        timeOfDeath: null,
    },
    {
        id: 7,
        name: 'Atroce',
        map: 'ra_fild03',
        spawnTime: { minMinutes: 180, maxMinutes: 190 },
        sprite: '1785.png',
        timeOfDeath: null,
    },
    {
        id: 10,
        name: 'Atroce',
        map: 've_fild02',
        spawnTime: { minMinutes: 360, maxMinutes: 370 },
        sprite: '1785.png',
        timeOfDeath: null,
    },
    {
        id: 6,
        name: 'Atroce',
        map: 'ra_fild02',
        spawnTime: { minMinutes: 240, maxMinutes: 250 },
        sprite: '1785.png',
        timeOfDeath: null,
    },
    {
        id: 9,
        name: 'Atroce',
        map: 've_fild01',
        spawnTime: { minMinutes: 180, maxMinutes: 190 },
        sprite: '1785.png',
        timeOfDeath: null,
    },
    {
        id: 11,
        name: 'Bacsojin/White Lady',
        map: 'lou_dun03',
        spawnTime: { minMinutes: 117, maxMinutes: 127 },
        sprite: '1518.png',
        timeOfDeath: null,
    },
    {
        id: 12,
        name: 'Baphomet',
        map: 'prt_maze03',
        spawnTime: { minMinutes: 120, maxMinutes: 130 },
        sprite: '1039.png',
        timeOfDeath: null,
    },
    {
        id: 13,
        name: 'Beelzebub',
        map: 'abbey03',
        spawnTime: { minMinutes: 720, maxMinutes: 730 },
        sprite: '1874.png',
        timeOfDeath: null,
    },
    {
        id: 14,
        name: 'Bio3 MVP',
        map: 'lhz_dun03',
        spawnTime: { minMinutes: 100, maxMinutes: 130 },
        sprite: 'lhz_dun03.png',
        timeOfDeath: null,
    },
    {
        id: 83,
        name: 'Bloody Knight',
        map: 'gl_knt02',
        spawnTime: { minMinutes: 60, maxMinutes: 90 },
        sprite: '1268.png',
        timeOfDeath: null,
    },
    {
        id: 15,
        name: 'Boitata',
        map: 'bra_dun02',
        spawnTime: { minMinutes: 120, maxMinutes: 130 },
        sprite: '2068.png',
        timeOfDeath: null,
    },
    {
        id: 101,
        name: 'Corrupted Soul',
        map: 'OGH 1',
        spawnTime: { minMinutes: 960, maxMinutes: 961 },
        sprite: '2475.png',
        timeOfDeath: null,
    },
    {
        id: 16,
        name: 'Dark Lord',
        map: 'gld_dun04',
        spawnTime: { minMinutes: 480, maxMinutes: 490 },
        sprite: '1272.png',
        timeOfDeath: null,
    },
    {
        id: 17,
        name: 'Dark Lord',
        map: 'gl_chyard',
        spawnTime: { minMinutes: 60, maxMinutes: 70 },
        sprite: '1272.png',
        timeOfDeath: null,
    },
    {
        id: 18,
        name: 'Detale',
        map: 'abyss_03',
        spawnTime: { minMinutes: 180, maxMinutes: 190 },
        sprite: '1719.png',
        timeOfDeath: null,
    },
    {
        id: 70,
        name: 'Deviling',
        map: 'yuno_fild03',
        spawnTime: { minMinutes: 60, maxMinutes: 90 },
        sprite: '1582.png',
        timeOfDeath: null,
    },
    {
        id: 19,
        name: 'Deviling',
        map: 'pay_fild04',
        spawnTime: { minMinutes: 120, maxMinutes: 180 },
        sprite: '1582.png',
        timeOfDeath: null,
    },
    {
        id: 20,
        name: 'Deviling',
        map: 'yuno_fild03',
        spawnTime: { minMinutes: 60, maxMinutes: 90 },
        sprite: '1582.png',
        timeOfDeath: null,
    },
    {
        id: 21,
        name: 'Doppelganger',
        map: 'gef_dun02',
        spawnTime: { minMinutes: 120, maxMinutes: 130 },
        sprite: '1046.png',
        timeOfDeath: null,
    },
    {
        id: 22,
        name: 'Doppelganger',
        map: 'gld_dun02',
        spawnTime: { minMinutes: 480, maxMinutes: 490 },
        sprite: '1046.png',
        timeOfDeath: null,
    },
    {
        id: 23,
        name: 'Dracula',
        map: 'gef_dun01',
        spawnTime: { minMinutes: 60, maxMinutes: 70 },
        sprite: '1389.png',
        timeOfDeath: null,
    },
    {
        id: 24,
        name: 'Drake',
        map: 'treasure02',
        spawnTime: { minMinutes: 120, maxMinutes: 130 },
        sprite: '1112.png',
        timeOfDeath: null,
    },
    {
        id: 96,
        name: 'Duneyrr 1',
        map: 'nyd_01',
        spawnTime: { minMinutes: 15, maxMinutes: 15 },
        sprite: '2018.png',
        timeOfDeath: null,
    },
    {
        id: 966,
        name: 'Duneyrr 2',
        map: 'nyd_01',
        spawnTime: { minMinutes: 15, maxMinutes: 15 },
        sprite: '2018.png',
        timeOfDeath: null,
    },
    {
        id: 25,
        name: 'Eddga',
        map: 'gld_dun01',
        spawnTime: { minMinutes: 480, maxMinutes: 490 },
        sprite: '1115.png',
        timeOfDeath: null,
    },
    {
        id: 26,
        name: 'Eddga',
        map: 'pay_fild11',
        spawnTime: { minMinutes: 120, maxMinutes: 130 },
        sprite: '1115.png',
        timeOfDeath: null,
    },
    {
        id: 27,
        name: 'Egnigem Cenia',
        map: 'lhz_dun02',
        spawnTime: { minMinutes: 120, maxMinutes: 130 },
        sprite: '1658.png',
        timeOfDeath: null,
    },
    {
        id: 28,
        name: 'Evil Snake Lord',
        map: 'gon_dun03',
        spawnTime: { minMinutes: 94, maxMinutes: 104 },
        sprite: '1418.png',
        timeOfDeath: null,
    },
    {
        id: 29,
        name: 'Fallen Bishop Hibram',
        map: 'abbey02',
        spawnTime: { minMinutes: 120, maxMinutes: 130 },
        sprite: '1871.png',
        timeOfDeath: null,
    },
    {
        id: 30,
        name: 'Garm',
        map: 'xmas_fild01',
        spawnTime: { minMinutes: 120, maxMinutes: 130 },
        sprite: '1252.png',
        timeOfDeath: null,
    },
    {
        id: 73,
        name: 'Ghostring',
        map: 'prt_maze03',
        spawnTime: { minMinutes: 113, maxMinutes: 170 },
        sprite: '1120.png',
        timeOfDeath: null,
    },
    {
        id: 72,
        name: 'Ghostring',
        map: 'treasure02',
        spawnTime: { minMinutes: 33, maxMinutes: 53 },
        sprite: '1120.png',
        timeOfDeath: null,
    },
    {
        id: 31,
        name: 'Ghostring',
        map: 'gld_dun04',
        spawnTime: { minMinutes: 240, maxMinutes: 360 },
        sprite: '1120.png',
        timeOfDeath: null,
    },
    {
        id: 32,
        name: 'Ghostring',
        map: 'pay_fild04',
        spawnTime: { minMinutes: 60, maxMinutes: 90 },
        sprite: '1120.png',
        timeOfDeath: null,
    },
    {
        id: 34,
        name: 'Gloom Under Night',
        map: 'ra_san05',
        spawnTime: { minMinutes: 300, maxMinutes: 310 },
        sprite: '1768.png',
        timeOfDeath: null,
    },
    {
        id: 33,
        name: 'Golden Thief Bug',
        map: 'prt_sewb4',
        spawnTime: { minMinutes: 60, maxMinutes: 70 },
        sprite: '1086.png',
        timeOfDeath: null,
    },
    {
        id: 97,
        name: 'Gopinch',
        map: 'mosk_dun03',
        spawnTime: { minMinutes: 120, maxMinutes: 130 },
        sprite: '1885.png',
        timeOfDeath: null,
    },
    {
        id: 82,
        name: 'Green Maiden',
        map: 'lou_dun03',
        spawnTime: { minMinutes: 50, maxMinutes: 80 },
        sprite: '1631.png',
        timeOfDeath: null,
    },
    {
        id: 35,
        name: 'Hardrock Mammoth',
        map: 'man_fild03',
        spawnTime: { minMinutes: 240, maxMinutes: 240 },
        sprite: '1990.png',
        timeOfDeath: null,
    },
    {
        id: 36,
        name: 'Ifrit',
        map: 'thor_v03',
        spawnTime: { minMinutes: 660, maxMinutes: 670 },
        sprite: '1832.png',
        timeOfDeath: null,
    },
    {
        id: 37,
        name: 'Incantation Samurai',
        map: 'ama_dun03',
        spawnTime: { minMinutes: 91, maxMinutes: 101 },
        sprite: '1492.png',
        timeOfDeath: null,
    },
    {
        id: 38,
        name: 'Kiel D-01',
        map: 'kh_dun02',
        spawnTime: { minMinutes: 120, maxMinutes: 180 },
        sprite: '1734.png',
        timeOfDeath: null,
    },
    {
        id: 98,
        name: 'Kraken',
        map: 'iz_dun05',
        spawnTime: { minMinutes: 120, maxMinutes: 150 },
        sprite: '2202.png',
        timeOfDeath: null,
    },
    {
        id: 39,
        name: 'Ktullanux',
        map: 'ice_dun03',
        spawnTime: { minMinutes: 120, maxMinutes: 120 },
        sprite: '1779.png',
        timeOfDeath: null,
    },
    {
        id: 89,
        name: 'Ktullanux PS',
        map: '',
        spawnTime: { minMinutes: 240, maxMinutes: 245 },
        sprite: '1779.png',
        timeOfDeath: null,
    },
    {
        id: 40,
        name: 'Lady Tanee',
        map: 'ayo_dun02',
        spawnTime: { minMinutes: 420, maxMinutes: 430 },
        sprite: '1688.png',
        timeOfDeath: null,
    },
    {
        id: 41,
        name: 'Lord of Death',
        map: 'nifflheim',
        spawnTime: { minMinutes: 133, maxMinutes: 133 },
        sprite: '21579.png',
        timeOfDeath: null,
    },
    {
        id: 43,
        name: 'Maya',
        map: 'gld_dun03',
        spawnTime: { minMinutes: 480, maxMinutes: 490 },
        sprite: '1289.png',
        timeOfDeath: null,
    },
    {
        id: 42,
        name: 'Maya',
        map: 'anthell02',
        spawnTime: { minMinutes: 120, maxMinutes: 130 },
        sprite: '1289.png',
        timeOfDeath: null,
    },
    {
        id: 44,
        name: 'Maya Purple',
        map: 'anthell01',
        spawnTime: { minMinutes: 120, maxMinutes: 180 },
        sprite: '1147.png',
        timeOfDeath: null,
    },
    {
        id: 45,
        name: 'Maya Purple',
        map: 'gld_dun03',
        spawnTime: { minMinutes: 20, maxMinutes: 30 },
        sprite: '1147.png',
        timeOfDeath: null,
    },
    {
        id: 91,
        name: 'Maya Purple01 GD',
        map: 'gld_dun03',
        spawnTime: { minMinutes: 20, maxMinutes: 30 },
        sprite: '1147.png',
        timeOfDeath: null,
    },
    {
        id: 92,
        name: 'Maya Purple02 GD',
        map: 'gld_dun03',
        spawnTime: { minMinutes: 20, maxMinutes: 30 },
        sprite: '1147.png',
        timeOfDeath: null,
    },
    {
        id: 93,
        name: 'Maya Purple03 GD',
        map: 'gld_dun03',
        spawnTime: { minMinutes: 20, maxMinutes: 30 },
        sprite: '1147.png',
        timeOfDeath: null,
    },
    {
        id: 46,
        name: 'Mistress',
        map: 'mjolnir_04',
        spawnTime: { minMinutes: 120, maxMinutes: 130 },
        sprite: '1059.png',
        timeOfDeath: null,
    },
    {
        id: 47,
        name: 'Moonlight Flower',
        map: 'pay_dun04',
        spawnTime: { minMinutes: 60, maxMinutes: 70 },
        sprite: '1150.png',
        timeOfDeath: null,
    },
    {
        id: 86,
        name: 'Mutant Dragonoid',
        map: 'cmd_fild03',
        spawnTime: { minMinutes: 30, maxMinutes: 35 },
        sprite: '1262.png',
        timeOfDeath: null,
    },
    {
        id: 49,
        name: 'Orc Hero',
        map: 'gef_fild14',
        spawnTime: { minMinutes: 60, maxMinutes: 70 },
        sprite: '1087.png',
        timeOfDeath: null,
    },
    {
        id: 48,
        name: 'Orc Hero',
        map: 'gef_fild02',
        spawnTime: { minMinutes: 1440, maxMinutes: 1450 },
        sprite: '1087.png',
        timeOfDeath: null,
    },
    {
        id: 50,
        name: 'Orc Lord',
        map: 'gef_fild10',
        spawnTime: { minMinutes: 120, maxMinutes: 130 },
        sprite: '1190.png',
        timeOfDeath: null,
    },
    {
        id: 51,
        name: 'Osiris',
        map: 'moc_pryd04',
        spawnTime: { minMinutes: 60, maxMinutes: 70 },
        sprite: '1038.png',
        timeOfDeath: null,
    },
    {
        id: 52,
        name: 'Pharaoh',
        map: 'in_sphinx5',
        spawnTime: { minMinutes: 60, maxMinutes: 70 },
        sprite: '1157.png',
        timeOfDeath: null,
    },
    {
        id: 53,
        name: 'Phreeoni',
        map: 'moc_fild17',
        spawnTime: { minMinutes: 120, maxMinutes: 130 },
        sprite: '1159.png',
        timeOfDeath: null,
    },
    {
        id: 54,
        name: 'RSX_0806',
        map: 'ein_dun02',
        spawnTime: { minMinutes: 125, maxMinutes: 135 },
        sprite: '1623.png',
        timeOfDeath: null,
    },
    {
        id: 55,
        name: 'Stormy Knight',
        map: 'xmas_dun02',
        spawnTime: { minMinutes: 60, maxMinutes: 70 },
        sprite: '1251.png',
        timeOfDeath: null,
    },
    {
        id: 56,
        name: 'Tao Gunka',
        map: 'beach_dun',
        spawnTime: { minMinutes: 300, maxMinutes: 310 },
        sprite: '3430.png',
        timeOfDeath: null,
    },
    {
        id: 57,
        name: 'Tendrillion',
        map: 'spl_fild03',
        spawnTime: { minMinutes: 60, maxMinutes: 60 },
        sprite: '1991.png',
        timeOfDeath: null,
    },
    {
        id: 58,
        name: 'Thanatos',
        map: 'thana_boss',
        spawnTime: { minMinutes: 120, maxMinutes: 120 },
        sprite: '1708.png',
        timeOfDeath: null,
    },
    {
        id: 100,
        name: 'Toad',
        map: 'cmd_fild03',
        spawnTime: { minMinutes: 60, maxMinutes: 90 },
        sprite: '1089.png',
        timeOfDeath: null,
    },
    {
        id: 99,
        name: 'Toad',
        map: 'gef_fild01',
        spawnTime: { minMinutes: 60, maxMinutes: 90 },
        sprite: '1089.png',
        timeOfDeath: null,
    },
    {
        id: 59,
        name: 'Turtle General',
        map: 'tur_dun04',
        spawnTime: { minMinutes: 60, maxMinutes: 70 },
        sprite: '1312.png',
        timeOfDeath: null,
    },
    {
        id: 60,
        name: 'Valkyrie 1',
        map: 'odin_tem03',
        spawnTime: { minMinutes: 30, maxMinutes: 30 },
        sprite: '2037.png',
        timeOfDeath: null,
    },
    {
        id: 61,
        name: 'Valkyrie 2',
        map: 'odin_tem03',
        spawnTime: { minMinutes: 30, maxMinutes: 30 },
        sprite: '2037.png',
        timeOfDeath: null,
    },
    {
        id: 62,
        name: 'Valkyrie 3',
        map: 'odin_tem02',
        spawnTime: { minMinutes: 90, maxMinutes: 90 },
        sprite: '2037.png',
        timeOfDeath: null,
    },
    {
        id: 63,
        name: 'Valkyrie Randgris',
        map: 'odin_tem03',
        spawnTime: { minMinutes: 480, maxMinutes: 490 },
        sprite: '1751.png',
        timeOfDeath: null,
    },
    {
        id: 64,
        name: 'Vesper',
        map: 'jupe_core',
        spawnTime: { minMinutes: 120, maxMinutes: 130 },
        sprite: '1685.png',
        timeOfDeath: null,
    },
    {
        id: 65,
        name: 'Wounded Morroc',
        map: 'moc_fild22',
        spawnTime: { minMinutes: 720, maxMinutes: 780 },
        sprite: '1917.png',
        timeOfDeath: null,
    },
    {
        id: 12591,
        name: 'Gryphon 1',
        map: 'ra_fild01',
        spawnTime: { minMinutes: 60, maxMinutes: 60 },
        sprite: '1259.png',
    },
    {
        id: 12592,
        name: 'Gryphon 2',
        map: 'ra_fild01',
        spawnTime: { minMinutes: 60, maxMinutes: 60 },
        sprite: '1259.png',
    },
    {
        id: 12593,
        name: 'Gryphon 3',
        map: 'ra_fild01',
        spawnTime: { minMinutes: 60, maxMinutes: 60 },
        sprite: '1259.png',
    },
] as RagnarokMvp[]
