export default [
    { name: 'International Date Line West', gmt: 'GMT-12:00', iana: 'Etc/GMT+12' },
    { name: 'Midway Island, Samoa', gmt: 'GMT-11:00', iana: 'Pacific/Midway' },
    { name: 'Hawaii', gmt: 'GMT-10:00', iana: 'Pacific/Honolulu' },
    { name: 'Alaska', gmt: 'GMT-09:00', iana: 'America/Anchorage' },
    { name: 'Pacific Time (US & Canada)', gmt: 'GMT-08:00', iana: 'America/Los_Angeles' },
    { name: 'Mountain Time (US & Canada)', gmt: 'GMT-07:00', iana: 'America/Denver' },
    { name: 'Central Time (US & Canada)', gmt: 'GMT-06:00', iana: 'America/Chicago' },
    { name: 'Eastern Time (US & Canada)', gmt: 'GMT-05:00', iana: 'America/New_York' },
    { name: 'Atlantic Time (Canada)', gmt: 'GMT-04:00', iana: 'America/Halifax' },
    { name: 'Buenos Aires, São Paulo', gmt: 'GMT-03:00', iana: 'America/Argentina/Buenos_Aires' },
    { name: 'Fernando de Noronha', gmt: 'GMT-02:00', iana: 'America/Noronha' },
    { name: 'Azores, Cape Verde Islands', gmt: 'GMT-01:00', iana: 'Atlantic/Azores' },
    { name: 'London, Dublin, Lisbon', gmt: 'GMT+00:00', iana: 'Europe/London' },
    { name: 'Berlin, Paris, Madrid, Rome', gmt: 'GMT+01:00', iana: 'Europe/Berlin' },
    { name: 'Athens, Helsinki, Istanbul, Cairo', gmt: 'GMT+02:00', iana: 'Europe/Athens' },
    { name: 'Moscow, St. Petersburg, Nairobi', gmt: 'GMT+03:00', iana: 'Europe/Moscow' },
    { name: 'Abu Dhabi, Muscat, Tbilisi', gmt: 'GMT+04:00', iana: 'Asia/Dubai' },
    { name: 'Islamabad, Karachi, Tashkent', gmt: 'GMT+05:00', iana: 'Asia/Karachi' },
    { name: 'Mumbai, Colombo, New Delhi', gmt: 'GMT+05:30', iana: 'Asia/Kolkata' },
    { name: 'Kathmandu', gmt: 'GMT+05:45', iana: 'Asia/Kathmandu' },
    { name: 'Almaty, Dhaka', gmt: 'GMT+06:00', iana: 'Asia/Dhaka' },
    { name: 'Bangkok, Hanoi, Jakarta', gmt: 'GMT+07:00', iana: 'Asia/Bangkok' },
    { name: 'Beijing, Hong Kong, Singapore', gmt: 'GMT+08:00', iana: 'Asia/Shanghai' },
    { name: 'Tokyo, Seoul', gmt: 'GMT+09:00', iana: 'Asia/Tokyo' },
    { name: 'Sydney, Melbourne, Brisbane', gmt: 'GMT+10:00', iana: 'Australia/Sydney' },
    { name: 'Magadan, Solomon Islands', gmt: 'GMT+11:00', iana: 'Pacific/Guadalcanal' },
    { name: 'Auckland, Wellington, Fiji', gmt: 'GMT+12:00', iana: 'Pacific/Auckland' },
    { name: "Nuku'alofa, Samoa", gmt: 'GMT+13:00', iana: 'Pacific/Tongatapu' },
]
